### ISSUE TITLE
Can you give me the plugin ? i'm not able to convert it to plugin because its showing a error "Caused by: java.lang.ClassNotFoundException: net.atlas.SkyblockSandbox.SBX"

### ISSUE THREAD

**Issue by Hypocraft** [Swofty-Developments/HypixelSkyblockRecode#6]

**Comment by Swofty-Developments** [comment]
Are you sure that you are correctly shading the plug-in? It should be able to access internal classes during runtime.

**Comment by Hypocraft** [comment]
> 

it shows error when i run it my discord is Hassaan_Abbas#5211 can you give me the plug-in please


i'm recreating dungeons so i need some hypixel items so far i've done first floor map design and some items

**Comment by Hypocraft** [comment]
and what's the version of the plug-in i'n running it on 1.8.9

**Comment by Swofty-Developments** [comment]
The plugin is based on 1.8.9, we haven’t used this core in over a year and the entire project is deprecated. None of us really remember the set up process, although I have heard that there has been people who have been able to set it up who I presume will make a pull request soon.

**Comment by Swofty-Developments** [comment]
The plugin is based on 1.8.9, we haven’t used this core in over a year and the entire project is deprecated. None of us really remember the set up process, although I have heard that there has been people who have been able to set it up who I presume will make a pull request soon.

**Comment by Hypocraft** [comment]
> The plugin is based on 1.8.9, we haven’t used this core in over a year and the entire project is deprecated. None of us really remember the set up process, although I have heard that there has been people who have been able to set it up who I presume will make a pull request soon.

can you try to make it please

**Comment by Hypocraft** [comment]
or if u have the jar file can you give me ?

**Comment by Swofty-Developments** [comment]
The JAR has been added as a release onto the GitHub page.
