### ISSUE TITLE
Error with the Citizens Dependency

### ISSUE THREAD

**Issue by olehrstm** [Swofty-Developments/HypixelSkyblockRecode#9]
Hello, I cloned the repo and changed the pom.xml like #7 but now I got this error `net.citizensnpcs:citizens-main:pom:2.0.27-SNAPSHOT was not found in https://jitpack.io during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of jitpack.io has elapsed or updates are forced`

**Comment by Hypocraft** [comment]
yoo did u managed to convert it to plugin?? if yes then pls give me i'm getting error

**Comment by Swofty-Developments** [comment]
Try it again now and get back to me.

**Comment by olehrstm** [comment]
Now im getting `Could not find artifact net.citizensnpcs:citizens-main:pom:2.0.29-SNAPSHOT in jitpack.io (https://jitpack.io)`

**Comment by Hypocraft** [comment]
> Now im getting `Could not find artifact net.citizensnpcs:citizens-main:pom:2.0.29-SNAPSHOT in jitpack.io (https://jitpack.io)`

reply pls

**Comment by Hypocraft** [comment]
> And when im trying to load the jar you uploaded im getting this error `[15:06:45 ERROR]: Error occurred while enabling SkyblockSandboxBase v0.1 (Is it up to date?) java.lang.IllegalArgumentException: The connection string is invalid. Connection strings must start with either 'mongodb://' or 'mongodb+srv:// at com.mongodb.ConnectionString.<init>(ConnectionString.java:293) ~[?:?] at com.mongodb.client.MongoClients.create(MongoClients.java:61) ~[?:?] at net.atlas.SkyblockSandbox.database.mongo.MongoCoins.connect(MongoCoins.java:43) ~[?:?] at net.atlas.SkyblockSandbox.SBX.onEnable(SBX.java:130) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-21fe707-741a1bd] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-21fe707-741a1bd] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-21fe707-741a1bd] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-21fe707-741a1bd] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-21fe707-741a1bd] at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-21fe707-741a1bd] at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-21fe707-741a1bd] at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-21fe707-741a1bd] at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-21fe707-741a1bd] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-21fe707-741a1bd] at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]`

CAN YOU PLEASE GIVE ME THE PLUGIN YOU MADE

**Comment by shadowlol2** [comment]
HypoCraft u need to put your own mongodb uri or else the plugin wont load as i said with my pull request
just compile it on your own its not that hard. U need to make a mongodb account then database then get the mongodb uri then paste it to the files In database/mongo/

**Comment by Hypocraft** [comment]
> HypoCraft u need to put your own mongodb uri or else the plugin wont load as i said with my pull request just compile it on your own its not that hard. U need to make a mongodb account then database then get the mongodb uri then paste it to the files In database/mongo/

ok thx

**Comment by shadowlol2** [comment]
if u need help dm me on discord or atlas discord server

**Comment by Hypocraft** [comment]
> if u need help dm me on discord or atlas discord server

your ign?
